language: elixir
sudo: false
env:
  global:
    # Follow other language's environment
    # e.g.) `RACK_ENV=test` has been setted as Default Environment Variables
    # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
    - MIX_ENV=test
elixir:
  - 1.4.2
cache:
  directories:
    - _build
    - deps
    - plt
otp_release:
  - 19.3
before_script:
  - mkdir -p plt && mix dialyzer.plt
script:
  - mix credo --strict
  - mix dialyzer --halt-exit-status
  - mix test
after_success:
  - mix hex.config username $HEX_USERNAME
  - mix hex.config key $HEX_KEY
  - yes | mix hex.publish
  - mix hex.docs
